INSERT INTO DISH (NAME, PRICE) VALUES ('Margerita', 99);
INSERT INTO DISH (NAME, PRICE) VALUES ('Funghi', 110);
INSERT INTO DISH (NAME, PRICE) VALUES ('Vegetariana', 110);
INSERT INTO DISH (NAME, PRICE) VALUES ('Quattro Stagioni', 120);
INSERT INTO DISH (NAME, PRICE) VALUES ('Frutti di Mare', 145);